/**
 * WuWa Log Decryptor - Logic & Cipher Implementation
 * Upgraded with robust validation and explicit error diagnostics.
 */

// --- Constants & LUTs ---
const HEADER_A = [0x00, 0x54, 0x50]; // TP
const HEADER_B = [0x00, 0x4C, 0x4F]; // LO
const BOM = [0xEF, 0xBB, 0xBF];

// Scheme A uses an alternating XOR key based on parity
const LUT_A = Uint8Array.from({ length: 256 }, (_, i) => (i & 1) ? (i ^ 0xA5) : (i ^ 0xEF));
// Scheme B uses a standard 0x55 XOR
const LUT_B = Uint8Array.from({ length: 256 }, (_, i) => i ^ 0x55);

// Crash Signatures to scan for
const CRASH_SIGNATURES = [
    { id: 'fsr3', pattern: /KuroFI_ShaderArchive_Failed/i, name: 'KuroFI Shader Archive' },
    { id: 'mfrc', pattern: /MFRC_INIT_FAILED/i, name: 'MFRC Init Failure' },
    { id: 'vulkan', pattern: /vkCreateSwapchainKHR/i, name: 'Vulkan Swapchain Mismatch' },
    { id: 'niagara', pattern: /NiagaraGPUInstanceCountManager/i, name: 'Niagara GPU Overflow' },
    { id: 'puerts', pattern: /Puerts/i, name: 'Puerts Race Condition' },
    { id: 'lgui', pattern: /LGUIRenderer/i, name: 'LGUI Null Dereference' }
];

let selectedFile = null;
let fullDecryptedText = "";

// --- UI Interaction Functions ---

function triggerFileInput() {
    document.getElementById('fileInput').click();
}

function handleDragOver(e) {
    e.preventDefault();
    document.getElementById('dropZone').classList.add('drag-over');
}

function handleDragLeave(e) {
    e.preventDefault();
    document.getElementById('dropZone').classList.remove('drag-over');
}

function handleDrop(e) {
    e.preventDefault();
    document.getElementById('dropZone').classList.remove('drag-over');
    if (e.dataTransfer.files.length > 0) {
        processFileSelection(e.dataTransfer.files[0]);
    }
}

function handleFileSelect(e) {
    if (e.target.files.length > 0) {
        processFileSelection(e.target.files[0]);
    }
}

function processFileSelection(file) {
    selectedFile = file;
    const infoBar = document.getElementById('fileInfoBar');
    const dropZone = document.getElementById('dropZone');

    document.getElementById('fileInfoName').textContent = file.name;
    document.getElementById('fileInfoSize').textContent = (file.size / 1024).toFixed(2) + " KB";

    infoBar.classList.add('visible');
    dropZone.classList.add('has-file');
    document.getElementById('decryptBtn').disabled = false;

    resetDetectionUI();
}

function resetDetectionUI() {
    document.getElementById('schemeDetector').classList.remove('visible');
    document.getElementById('dotA').classList.remove('active');
    document.getElementById('dotB').classList.remove('active');
    document.getElementById('dotPlain').classList.remove('active');
    document.getElementById('detectedScheme').textContent = "—";
}

// --- Enhanced Error Logging Handler ---

function handleDecryptionFailure(reason, details = "") {
    const output = document.getElementById('decryptedOutput');
    const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);

    // Construct readable error report
    const errorReport =
        `======================================================================
[ERROR] DECRYPTION PIPELINE FAILED
======================================================================
Timestamp : ${timestamp}
File Name : ${selectedFile ? selectedFile.name : "No file found"}
File Size : ${selectedFile ? selectedFile.size.toLocaleString() + " bytes" : "0 bytes"}
Failure   : ${reason}
----------------------------------------------------------------------
DIAGNOSTIC DETAILS:
${details}
----------------------------------------------------------------------
SUGGESTED ACTIONS:
1. Ensure this file is a genuine 'Client.log' generated by Wuthering Waves.
2. Confirm the file size is greater than 0 KB and isn't locked/corrupted.
3. If this file is completely plain, human-readable text already, 
   decryption operations are unnecessary.
======================================================================`;

    output.value = errorReport;

    // Clear display stats
    document.getElementById('statLines').textContent = "ERR";
    document.getElementById('statErrors').textContent = "1";
    document.getElementById('statWarnings').textContent = "0";

    // Disable searching/filtering since output is just an error report
    document.getElementById('searchInput').disabled = true;
    document.getElementById('filterErrors').disabled = true;

    // Enable copy/save buttons so users can share the diagnostic report if needed
    document.getElementById('copyDecBtn').disabled = false;
    document.getElementById('dlDecBtn').disabled = false;

    // Reset crash signature cards to default clean/pending state
    const cards = document.querySelectorAll('.sig-card');
    cards.forEach(card => {
        card.className = 'sig-card';
        const badge = card.querySelector('.sig-badge');
        badge.className = 'sig-badge pending';
        badge.textContent = '—';
    });

    // Reset detection UI state cleanly
    resetDetectionUI();
    document.getElementById('schemeDetector').classList.add('visible');
    document.getElementById('detectedScheme').textContent = "FAILED";

    // Clean up interface loader
    document.getElementById('decryptBtn').disabled = false;
    document.getElementById('progressWrap').classList.remove('visible');
}

// --- Decryption Implementation ---

async function decryptFile() {
    if (!selectedFile) {
        handleDecryptionFailure("Missing File", "No file object found in runtime context.");
        return;
    }

    // 1. Initial Validation: Check if empty
    if (selectedFile.size === 0) {
        handleDecryptionFailure("Empty File Target", "The selected file contains 0 bytes of data and cannot be parsed.");
        return;
    }

    const btn = document.getElementById('decryptBtn');
    const progressWrap = document.getElementById('progressWrap');
    const progressBar = document.getElementById('progressBar');

    btn.disabled = true;
    progressWrap.classList.add('visible');
    progressBar.style.width = "20%";

    const reader = new FileReader();

    reader.onerror = function (e) {
        handleDecryptionFailure("Browser Core File System Error", `FileReader Event triggered an abort or error rule: ${reader.error?.message || "Unknown FS break."}`);
    };

    reader.onload = function (e) {
        try {
            const buffer = new Uint8Array(e.target.result);
            progressBar.style.width = "50%";

            // 2. Structural Check: Check if file has at least enough space for headers
            if (buffer.length < 3) {
                handleDecryptionFailure(
                    "Truncated Header Signature",
                    `The log file context is only ${buffer.length} bytes long. It is physically too small to hold valid Kuro Games magic decryption tags.`
                );
                return;
            }

            let scheme = null;
            let decryptedData;

            // Header Matching
            if (buffer[0] === HEADER_A[0] && buffer[1] === HEADER_A[1] && buffer[2] === HEADER_A[2]) {
                scheme = 'A';
            } else if (buffer[0] === HEADER_B[0] && buffer[1] === HEADER_B[1] && buffer[2] === HEADER_B[2]) {
                scheme = 'B';
            }

            document.getElementById('schemeDetector').classList.add('visible');

            // 3. File content evaluation criteria
            if (scheme) {
                const lut = (scheme === 'A') ? LUT_A : LUT_B;
                const body = buffer.slice(3);

                if (body.length === 0) {
                    handleDecryptionFailure("Zero Body Payloads", `The encryption signatures sequence match Scheme ${scheme}, but there are zero remaining bytes to decode inside the file stream layout.`);
                    return;
                }

                decryptedData = new Uint8Array(body.length);
                for (let i = 0; i < body.length; i++) {
                    decryptedData[i] = lut[body[i]];
                }

                document.getElementById(scheme === 'A' ? 'dotA' : 'dotB').classList.add('active');
                document.getElementById('detectedScheme').textContent = `Scheme ${scheme}`;
            } else {
                // Not Scheme A or B. Let's see if it looks like plain text or a completely different asset.
                // We test the first 16 bytes to check if it's printable plain text characters.
                let unprintableCount = 0;
                const sampleLength = Math.min(buffer.length, 32);

                for (let i = 0; i < sampleLength; i++) {
                    // Typical ASCII/UTF text values are generally >= 32 (or tabs 9, newlines 10/13)
                    const ch = buffer[i];
                    if (ch < 32 && ch !== 9 && ch !== 10 && ch !== 13) {
                        unprintableCount++;
                    }
                }

                // If it contains multiple arbitrary binary bytes, it's not plaintext log data
                if (unprintableCount > 3) {
                    handleDecryptionFailure(
                        "Unknown Encryption Signature or Binary Asset",
                        `Hex Headers: [${Array.from(buffer.slice(0, 5)).map(b => b.toString(16).toUpperCase().padStart(2, '0')).join(' ')}]\n` +
                        `This target contains illegal binary sequences. It is neither a Scheme A/B log, nor is it raw, unencrypted log plain text.`
                    );
                    return;
                }

                // Treat safely as structural Plaintext fallback
                decryptedData = buffer;
                document.getElementById('dotPlain').classList.add('active');
                document.getElementById('detectedScheme').textContent = "Plaintext";
            }

            progressBar.style.width = "80%";

            // 4. Decode validation
            const decoder = new TextDecoder("utf-8", { fatal: true });
            try {
                fullDecryptedText = decoder.decode(decryptedData);
            } catch (utf8Error) {
                handleDecryptionFailure(
                    "String Decoding Constraint Violation (UTF-8 Error)",
                    "Decryption mechanics ran successfully, but the resulting array contained malformed characters or non-UTF8 binary text definitions, breaking structural parsing logic."
                );
                return;
            }

            finalizeUI(fullDecryptedText);

        } catch (globalCatch) {
            handleDecryptionFailure("Unhandled Native Exception", globalCatch.stack || globalCatch.message || globalCatch);
        }
    };

    reader.readAsArrayBuffer(selectedFile);
}

function finalizeUI(text) {
    const output = document.getElementById('decryptedOutput');
    output.value = text;

    const lines = text.split('\n');
    document.getElementById('statLines').textContent = lines.length.toLocaleString();

    const errorCount = (text.match(/\[Error\]|error:|failed/gi) || []).length;
    const warnCount = (text.match(/\[Warning\]|warning:/gi) || []).length;

    document.getElementById('statErrors').textContent = errorCount;
    document.getElementById('statWarnings').textContent = warnCount;

    document.getElementById('searchInput').disabled = false;
    document.getElementById('filterErrors').disabled = false;
    document.getElementById('copyDecBtn').disabled = false;
    document.getElementById('dlDecBtn').disabled = false;

    scanSignatures(text);

    document.getElementById('progressBar').style.width = "100%";
    setTimeout(() => {
        document.getElementById('progressWrap').classList.remove('visible');
        document.getElementById('decryptBtn').disabled = false;
    }, 500);
}

function scanSignatures(text) {
    const cards = document.querySelectorAll('.sig-card');

    CRASH_SIGNATURES.forEach((sig, index) => {
        const found = sig.pattern.test(text);
        const card = cards[index];
        const badge = card.querySelector('.sig-badge');

        card.classList.remove('found', 'clean'); // reset
        if (found) {
            card.classList.add('found');
            badge.className = 'sig-badge found';
            badge.textContent = 'FOUND';
        } else {
            card.classList.add('clean');
            badge.className = 'sig-badge clean';
            badge.textContent = 'CLEAN';
        }
    });
}

// --- Utility Actions ---

function searchLog(query) {
    const output = document.getElementById('decryptedOutput');
    if (!query) {
        output.value = fullDecryptedText;
        return;
    }
    const lines = fullDecryptedText.split('\n');
    const filtered = lines.filter(line => line.toLowerCase().includes(query.toLowerCase()));
    output.value = filtered.join('\n');
}

function toggleErrorFilter() {
    const btn = document.getElementById('filterErrors');
    const isActive = btn.classList.toggle('active');

    if (isActive) {
        btn.style.background = "var(--jade-mid)";
        const lines = fullDecryptedText.split('\n');
        const filtered = lines.filter(line => /error|failed|fatal/gi.test(line));
        document.getElementById('decryptedOutput').value = filtered.join('\n');
    } else {
        btn.style.background = "";
        document.getElementById('decryptedOutput').value = fullDecryptedText;
    }
}

function copyDecrypted() {
    const output = document.getElementById('decryptedOutput');
    output.select();
    document.execCommand('copy');
}

function downloadDecrypted() {
    const blob = new Blob([document.getElementById('decryptedOutput').value], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = selectedFile ? `decrypted_${selectedFile.name.replace('.log', '')}.txt` : 'Client_Decrypted.txt';
    a.click();
    URL.revokeObjectURL(url);
}

function clearDecryptor() {
    selectedFile = null;
    fullDecryptedText = "";
    document.getElementById('fileInput').value = "";
    document.getElementById('decryptedOutput').value = "";
    document.getElementById('fileInfoBar').classList.remove('visible');
    document.getElementById('dropZone').classList.remove('has-file');
    document.getElementById('decryptBtn').disabled = true;

    document.getElementById('statLines').textContent = "—";
    document.getElementById('statErrors').textContent = "—";
    document.getElementById('statWarnings').textContent = "—";

    resetDetectionUI();
}