;		WuWa Mobile Config for Version 3.3
; 		   Last Modified by: Arglax
; ============================================================
; 			Stable Config (High-End)
; Link: https://github.com/Arglax/Mobile-WuWa-Config/blob/main/%5BV3.x%5D%20Working%20Configs/Stable%20Config/Engine.ini
; ============================================================
; 			ChangeLog:
; March 20, 2026 (Recommended Update)
; 1. Removed forbidden cvars
; 2. Raised DeviceScore to 4000 since 2000 now sometimes trigger the AUTOFPS prompt (weird lol)
; 		Final Notes
; - Change r.MobileContentScaleFactor to 1.0 or 1.25 for better performance/fps
; ============================================================
; 			References Used:
; 1. Archived Mobile Configs by AlteriaX 	(https://github.com/AlteriaX/WuWa-Configs-Android/tree/main)
; 2. UE Official CVar Reference 	(https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-console-variables-reference)
;====================END OF MAIN NOTES=======================
[StableConfigA DeviceProfile]
DeviceScore=99999
;Cvars=r.MobileContentScaleFactor=1.5
;CVars=r.SecondaryScreenPercentage.GameViewport=100
Cvars=r.Mobile.DeviceEvaluation=3
Cvars=r.Mobile.HighQualityMaterial=1
Cvars=r.Android.DisableVulkanSupport=0
CVars=r.Mobile.EnergySavingFrameInterpolation=0
Cvars=r.imp.SSMbScaleLod0=0.750
Cvars=r.imp.SSMbScaleLod1=1.750
Cvars=r.FEstimation.Option=1
CVars=sg.ViewDistanceQuality=3
CVars=sg.AntiAliasingQuality=3
CVars=sg.ShadowQuality=3	
CVars=sg.PostProcessQuality=4
CVars=sg.TextureQuality=3
CVars=sg.EffectsQuality=2	
CVars=sg.FoliageQuality=3
CVars=sg.ShadingQuality=3	
;This will give you frame generation
Cvars=r.KuroFI.Enable=1

[Android_Default DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_TegraK1 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G61x DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_Immortalis DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_Gx_Ultra DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G92x DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_MTK_6991 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_IMG_BXM DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G57_MC2 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G720 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno_7xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno740 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno_6xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno825 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno840 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno830 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno_8xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno810 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Xclipse9xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Xclipse940 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno7xx_Low DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Xclipse930 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Xclipse5xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G68 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Tensor_G4 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Tensor_G3 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000