;		WuWa Mobile Config for Version 3.5
; 		   Last Modified by: Arglax
; ============================================================
; 			Stable Config (High-End)
; Link: https://github.com/Arglax/Mobile-WuWa-Config/blob/main/%5BV3.x%5D%20Working%20Configs/Stable%20Configs/A%20High-End/DeviceProfiles.ini
; ============================================================
; 			ChangeLog:
; July 14, 2026
; 1. Added wp. and fix for bike frame gen artifact
; ============================================================
; 			References Used:
; 1. Archived Mobile Configs by AlteriaX 	(https://github.com/AlteriaX/WuWa-Configs-Android/tree/main)
; 2. UE Official CVar Reference 	(https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-console-variables-reference)
; 3. k4irzw67's frame gen issue fix
;====================END OF MAIN NOTES=======================
[StableConfigA DeviceProfile]
CVars=t.MaxFPS=120
Cvars=r.Mobile.DeviceEvaluation=3
Cvars=r.Mobile.HighQualityMaterial=1
Cvars=r.Android.DisableVulkanSupport=0
CVars=r.Mobile.EnergySavingFrameInterpolation=0
Cvars=r.imp.SSMbScaleLod0=0.750
Cvars=r.imp.SSMbScaleLod1=1.750
CVars=sg.ViewDistanceQuality=3
CVars=sg.AntiAliasingQuality=3
CVars=sg.ShadowQuality=3	
CVars=sg.PostProcessQuality=6
CVars=sg.TextureQuality=6
CVars=sg.EffectsQuality=2	
CVars=sg.FoliageQuality=3
CVars=sg.ShadingQuality=3
CVars=wp.Runtime.LoadingRangeScale=0.85
CVars=wp.Runtime.PlannedLoadingRangeScale=1.05
CVars=r.KuroFI.EnableSingleOcclusionBloomReplace=1
CVars=r.KuroFI.InternalResolutionScale=0.5
CVars=r.KuroFI.Enable=1

[Android_Default DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_TegraK1 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G61x DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_Immortalis DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_Gx_Ultra DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G92x DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_MTK_6991 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_IMG_BXM DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G57_MC2 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G720 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno_7xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno740 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno_6xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno825 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno840 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno830 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno_8xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno810 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Xclipse9xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Xclipse940 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Adreno7xx_Low DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Xclipse930 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Xclipse5xx DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Mali_G68 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Tensor_G4 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000

[Android_Tensor_G3 DeviceProfile]
BaseProfileName=StableConfigA
DeviceScore=5000
