;		WuWa Mobile Config for Version 3.5
; 		   Last Modified by: Arglax
; ============================================================
; 			Stable Config (Low-End)
; Link: https://github.com/Arglax/Mobile-WuWa-Config/blob/main/%5BV3.x%5D%20Working%20Configs/Stable%20Configs/C%20Low-End/DeviceProfiles.ini
; ============================================================
; 			ChangeLog:
; July 14, 2026
; 1. Optimization patch + bike frame gen fix
; ============================================================
; 			References Used:
; 1. Archived Mobile Configs by AlteriaX 	(https://github.com/AlteriaX/WuWa-Configs-Android/tree/main)
; 2. UE Official CVar Reference 	(https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-console-variables-reference)
; 3. k4irzw67's frame gen issue fix
;====================END OF MAIN NOTES=======================

[Android_Low DeviceProfile]
Cvars=r.Android.DisableVulkanSupport=0
Cvars=r.Android.VulkanSetting=1
Cvars=r.Mobile.HighQualityMaterial=1
Cvars=r.imp.SSMbScaleLod0=0.00
Cvars=r.imp.SSMbScaleLod1=0.00
CVars=wp.Runtime.LoadingRangeScale=0.6
CVars=wp.Runtime.PlannedLoadingRangeScale=0.95
CVars=sg.ViewDistanceQuality=0
CVars=sg.AntiAliasingQuality=0
CVars=sg.ShadowQuality=0
CVars=sg.PostProcessQuality=0
CVars=sg.TextureQuality=3
CVars=sg.EffectsQuality=0
CVars=sg.FoliageQuality=0
CVars=sg.ShadingQuality=1
CVars=r.Mobile.EnergySavingFrameInterpolation=0
CVars=r.DontLimitOnBattery=1