;		WuWa Mobile Config for Version 3.5
; 		   Last Modified by: Arglax
; ============================================================
; 			Stable Config (Low-End)
; Link: https://github.com/Arglax/Mobile-WuWa-Config/blob/main/%5BV3.x%5D%20Working%20Configs/Stable%20Configs/C%20Low-End/Engine.ini
; ============================================================
; 			ChangeLog:
; July 17, 2026
; 1. Added a.URO.Enable = 1
; 2. Added a.URO.ForceAnimRate = 2
; 3. Added a.URO.ForceInterpolation = 1
; 4. Added gc.ActorClusteringEnabled = 1
; 5. Added gc.AllowIncrementalGather = 1
; 6. Added gc.AllowIncrementalReachability = 1
; 7. Added gc.AllowParallelGC = 1
; 8. Added gc.AssetClusteringEnabled = 0
; 9. Added gc.ContinuousIncrementalGC = 1
; 10. Added gc.CreateGCClusters = 1
; 11. Added gc.FlushStreamingOnGC = 0
; 12. Added gc.IncrementalReachabilityTimeLimit = 0.002
; 13. Added gc.MaxObjectsInGame = 2000000
; 14. Added gc.MaxObjectsNotConsideredByGC = 80000
; 15. Added gc.MinDesiredObjectsPerSubTask = 128
; 16. Added gc.MultithreadedDestructionEnabled = 1
; 17. Added gc.SizeOfPermanentObjectPool = 33554432
; 18. Added gc.TimeBetweenPurgingPendingKillObjects = 60.0
; 19. Removed r.SSR.MaxRoughness (was 1.0)
; 20. Removed r.SSR.Quality (was 2)
; 21. Removed r.TemporalAA.Upscaler (was 1)
; 22. Removed r.Upscale.Quality (was 2)
; 23. r.LightShaftNumSamples changed from 4 to 8
; 24. r.Shadow.MinResolution changed from 64 to 32
; 25. r.TemporalAASamples changed from 8 to 12
; 26. r.Tonemapper.Quality changed from 4 to 5
; July 15, 2026
; 1. Removed r.Kuro.Foliage.FarCullDistanceMax (was 20000)
; 2. Removed r.Kuro.Foliage.GrassCullDistanceMax (was 15000)
; 3. Removed r.Kuro.Foliage.ImpostorFarCullDistanceMax (was 100000)
; 4. Removed r.Kuro.Foliage.MiddleCullDistanceMax (was 10000)
; 5. Removed r.Kuro.Foliage.NearCullDistanceMax (was 6000)
; 6. r.ScreenSizeCullRatioFactor changed from 3 to 5
; 7. wp.Runtime.PlannedLoadingRangeScale changed from 0.33 to 0.4

[SystemSettings]
a.URO.Enable=1
a.URO.ForceAnimRate=3 ;set to 2 if chars feel weird for u
a.URO.ForceInterpolation=1
r.SkinCache.SceneMemoryLimitInMB=128
wp.Runtime.LoadingRangeScale=0.33
wp.Runtime.PlannedLoadingRangeScale=0.4
r.MaxAnisotropy=0
r.Color.Mid=0.45
r.LightShaftAllowTAA=1
r.LightShaftBlurPasses=3
r.LightShaftDownSampleFactor=2
r.LightShaftFirstPassDistance=0.1
r.LightShaftNumSamples=8
r.LightShaftQuality=1
r.MotionBlurQuality=0
r.ParticleLODBias=0
r.ReflectionCaptureResolution=32
r.SSR.HalfResSceneColor=1
r.Shadow.MinResolution=32
r.ShadowQuality=4
r.Shadow.RadiusThreshold=0.02
r.TemporalAA.Algorithm=1
r.TemporalAA.AllowDownsampling=1
r.TemporalAACatmullRom=1
r.TemporalAACurrentFrameWeight=0.25
r.TemporalAAFilterSize=0.4
r.TemporalAA.HistoryScreenPercentage=70
r.TemporalAASamples=12
r.TemporalAA.Upsampling=1
r.Tonemapper.Quality=5
r.TonemapperGamma=2.05
Kuro.Blueprint.EnableGameBudget=1

[/Script/Engine.RendererSettings]
r.Android.DisableVulkanSupport=0
r.Kuro.Foliage.MobileFarCullDistanceMax=2000
r.Kuro.Foliage.MobileGrassCullDistanceMax=1500
r.Kuro.Foliage.MobileImpostorFarCullDistanceMax=10000
r.Kuro.Foliage.MobileMiddleCullDistanceMax=1000
r.Kuro.Foliage.MobileNearCullDistanceMax=600
r.Kuro.KuroBloomStreak=0
r.StaticMeshLODDistanceScale=0.95
r.DefaultBackBufferPixelFormat=0
r.SceneColorFormat=4
r.MaxAnisotropy=2

[/Script/Engine.RendererOverrideSettings]
r.ScreenSizeCullRatioFactor=5

[/Script/Engine.GarbageCollectionSettings]
gc.MinDesiredObjectsPerSubTask=128
gc.AllowParallelGC=1
gc.MultithreadedDestructionEnabled=1
gc.SizeOfPermanentObjectPool=1000000
gc.MaxObjectsInGame=1000000
gc.MaxObjectsNotConsideredByGC=80000
gc.CreateGCClusters=1
gc.ActorClusteringEnabled=1
gc.AssetClusteringEnabled=0
gc.AllowIncrementalReachability=1
gc.AllowIncrementalGather=1
gc.IncrementalReachabilityTimeLimit=0.002
gc.ContinuousIncrementalGC=1
gc.TimeBetweenPurgingPendingKillObjects=60.0
gc.FlushStreamingOnGC=0

[Core.System]
Paths=../../../Engine/Content
Paths=%GAMEDIR%Content
Paths=../../../Engine/Plugins/ThirdParty/ImpostorBaker/Content
Paths=../../../Engine/Plugins/json2struct/Content
Paths=../../../Engine/Plugins/Experimental/FieldSystemPlugin/Content
Paths=../../../Client/Plugins/LGUI/LGUI/Content
Paths=../../../Engine/Plugins/PrefabSystem/Content
Paths=../../../Engine/Plugins/FX/Niagara/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplay/Content
Paths=../../../Client/Plugins/Puerts/Puerts/Content
Paths=../../../Client/Plugins/Wwise/Content
Paths=../../../Engine/Plugins/Editor/GeometryMode/Content
Paths=../../../Engine/Plugins/MovieScene/SequencerScripting/Content
Paths=../../../Engine/Plugins/Experimental/PythonScriptPlugin/Content
Paths=../../../Client/Plugins/CrashSight/Content
Paths=../../../Engine/Plugins/ThirdParty/QuickEditor/Content
Paths=../../../Client/Plugins/Sharphereal/Content
Paths=../../../Engine/Plugins/Experimental/GeometryProcessing/Content
Paths=../../../Client/Plugins/Kuro/TASdkPlugin/Content
Paths=../../../Client/Plugins/Kuro/KRDataAnalyticsPlugin/Content
Paths=../../../Engine/Plugins/rdLODtools/Content
Paths=../../../Client/Plugins/AudioMaterialPlugin/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/DLSS/Content
Paths=../../../Engine/Plugins/Runtime/HoudiniEngine/Content
Paths=../../../Client/Plugins/Kuro/KuroHotPatch/Content
Paths=../../../Client/Plugins/Kuro/KuroImposter/Content
Paths=../../../Client/Plugins/Kuro/KuroAutomationTool/Content
Paths=../../../Engine/Plugins/FX/HoudiniNiagara/Content
Paths=../../../Client/Plugins/LogicDriverLite/Content
Paths=../../../Engine/Plugins/Runtime/AudioSynesthesia/Content
Paths=../../../Engine/Plugins/Experimental/ControlRig/Content
Paths=../../../Engine/Plugins/Media/MediaCompositing/Content
Paths=../../../Engine/Plugins/Runtime/Synthesis/Content
Paths=../../../Engine/Plugins/SequenceDialogue/Content
Paths=../../../Client/Plugins/Puerts/ReactUMG/Content
Paths=../../../Client/Plugins/genesis-ue-plugin/RenderExporter/Content
Paths=../../../Engine/Plugins/KuroiOSDelegate/Content
Paths=../../../Client/Plugins/Kuro/KuroCloudGame/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplayUI/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/OpacityMicroMap/Content
Paths=../../../Engine/Plugins/Experimental/ColorCorrectRegions/Content
Paths=../../../Client/Plugins/BlockoutToolsPlugin/Content
Paths=../../../Client/Plugins/ComfyTextures/Content
Paths=../../../Client/Plugins/KuroComputeShader/Content
Paths=../../../Client/Plugins/KuroTDM/Content
Paths=../../../Client/Plugins/Kuro/ImposterBaker/Content
Paths=../../../Client/Plugins/Kuro/KuroDynamicMeshBatch/Content
Paths=../../../Client/Plugins/Kuro/KuroGachaTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPerfCat/Content
Paths=../../../Client/Plugins/Kuro/KuroPSOTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPushSdk/Content
Paths=../../../Client/Plugins/MagtModule/Content
Paths=../../../Client/Plugins/SdkParamExtend/Content
Paths=../../../Client/Plugins/SpinePlugin/Content
Paths=../../../Client/Plugins/TpSafe/Content
Paths=../../../Engine/Plugins/AFME/Content
Paths=../../../Engine/Plugins/Animation/ACLPlugin/Content
Paths=../../../Engine/Plugins/AssetChecker/Content
Paths=../../../Engine/Plugins/AssetMemoryAnalyzer/Content
Paths=../../../Engine/Plugins/DawnSDK/DawnSDK/Content
Paths=../../../Engine/Plugins/Editor/SpeedTreeImporter/Content
Paths=../../../Engine/Plugins/Experimental/ChaosClothEditor/Content
Paths=../../../Engine/Plugins/Experimental/ChaosNiagara/Content
Paths=../../../Engine/Plugins/Experimental/ChaosSolverPlugin/Content
Paths=../../../Engine/Plugins/GSR/Content
Paths=../../../Engine/Plugins/MagicDawn/Content
Paths=../../../Engine/Plugins/MFRCModule/Content
Paths=../../../Engine/Plugins/Runtime/Intel/XeSS/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/NRD/Content
Paths=../../../Engine/Plugins/Compositing/OpenCVLensDistortion/Content
Paths=../../../Engine/Plugins/Experimental/FastGeoStreaming/Content
Paths=../../../Client/Plugins/Kuro/KuroWorldPartition/Content
Paths=../../../Client/Plugins/MeshBlend/Content
Paths=../../../Client/Plugins/TFlow/Content
Paths=../../../Engine/Plugins/KuroFI/Content
Paths=../../../Engine/Plugins/MTKCompensatedTimeStep/Content
Paths=../../../Engine/Plugins/MagtModule/Content

