;		WuWa Mobile Config for Version 3.6
; 		    Last Modified by: Arglax
; ============================================================
; 			Performance Config (Config_2)
; Link: https://github.com/Arglax/Mobile-WuWa-Config/tree/main/%5BV3.x%5D%20Working%20Configs/Performance%20Configs/Config_2
; ============================================================
; 		Change to your GPUFamily
; Link for PC Tutorial: https://youtu.be/gtmyFKGyl1M
; Link for Mobile Tutorial: https://youtube.com/shorts/ygf6GUBkx18
; ============================================================
; 			Final Notes
; 1. This DeviceProfiles.ini is plug and play. No required edits or changes in order to apply.
; ============================================================

[Android_High DeviceProfile]
DeviceScore=6969
CVars=r.imp.SSMbScaleLod0=0.00
CVars=r.imp.SSMbScaleLod1=0.00
CVars=r.Mobile.HighQualityMaterial=1
CVars=r.Android.DisableVulkanSupport=0     
CVars=wp.Runtime.LoadingRangeScale=0.7
CVars=wp.Runtime.PlannedLoadingRangeScale=0.95