;		WuWa Mobile Config for Version 3.5
; 		   Last Modified by: Arglax
; ============================================================
; 			Stable Config (Mid-End)
; Link: https://github.com/Arglax/Mobile-WuWa-Config/blob/main/%5BV3.x%5D%20Working%20Configs/Stable%20Configs/B%20Mid-End/Engine.ini
; ============================================================
; 			ChangeLog:
; July 20, 2026
; 1. Added r.MobileLightShaft = 1
; 2. Added r.MobileLightShaft.AllowTAA = 1
; 3. Added r.MobileLightShaft.NumSamples = 8
; 4. Added r.SSR.HalfResSceneColor = 1
; 5. Added r.VT.MaxUploadsPerFrame = 2
; 6. Added r.VT.MaxUploadsPerFrame.Streaming = 4
; 7. Removed r.MaxAnisotropy (was 16)
; 8. Removed r.Mobile.EnableLandscapeSSR (was 1)
; 9. Removed r.Mobile.WaterSSRResDiv (was 1.25)
; 10. Removed r.Mobile.WaterSSRStep (was 128)
; 11. Removed r.ShadowQuality (was 5)
; 12. a.URO.ForceAnimRate changed from 1 to 2
; 13. Kuro.Blueprint.EnableGameBudget changed from 0 to 1 ;set to 0 if u want honami escalator moving
; 14. r.LightShaftQuality changed from 2 to 1
; 15. r.Shadow.CSM.MaxCascades changed from 5 to 4
; 16. r.Shadow.PerObjectResolutionMax changed from 1024 to 768
; 17. r.SSR.MaxRoughness changed from 0.9 to 0.7
; 18. r.SSR.Quality changed from 3 to 2
; July 17, 2026
; 1. Added foliage.LODDistanceScale = 1.0
; 2. Added gc.ActorClusteringEnabled = 1
; 3. Added gc.AllowParallelGC = 1
; 4. Added gc.CreateGCClusters = 1
; 5. Added gc.FlushStreamingOnGC = 0
; 6. Added gc.MaxObjectsInGame = 2000000
; 7. Added gc.MaxObjectsNotConsideredByGC = 80000
; 8. Added gc.MinDesiredObjectsPerSubTask = 128
; 9. Added gc.MultithreadedDestructionEnabled = 1
; 10. Added gc.SizeOfPermanentObjectPool = 33554432
; 11. Added gc.TimeBetweenPurgingPendingKillObjects = 60.0
; 12. Added Kuro.Blueprint.EnableGameBudget = 0
; 13. Added r.DistanceFieldAO = 1
; 14. Added r.Kuro.AutoCoolEnable = 0
; 15. Added r.Kuro.Foliage.GrassCullDistanceMax = 18000
; 16. Added r.Kuro.InteractionEffect.UseCppWaterEffect = 1
; 17. Added r.LightShaftNumSamples = 12
; 18. Added r.LightShaftQuality = 2
; 19. Added r.MaxAnisotropy = 16
; 20. Added r.Mobile.EnableLandscapeSSR = 1
; 21. Added r.Mobile.WaterSSRResDiv = 1.25
; 22. Added r.Mobile.WaterSSRStep = 128
; 23. Added r.PostProcessAAQuality = 4
; 24. Added r.Shadow.CSM.MaxCascades = 5
; 25. Added r.Shadow.CSM0Distance = 1000
; 26. Added r.Shadow.CSM1Distance = 1500
; 27. Added r.Shadow.CSM2Distance = 5000
; 28. Added r.ShadowQuality = 5
; 29. Added r.SSR.Temporal = 1
; 30. Added r.Streaming.GroupBoost.CommonHLODTextureFactor = 0.8
; 31. Added r.Streaming.GroupBoost.HugeBuildingTextureFactor = 0.8
; 32. Added r.Streaming.GroupBoost.HugeFoliageTextureFactor = 0.8
; 33. Added r.Streaming.GroupBoost.HugeMonsterTextureFactor = 0.8
; 34. Added r.Streaming.GroupBoost.HugeNpcTextureFactor = 0.8
; 35. Added r.Streaming.GroupBoost.HugePropTextureFactor = 0.8
; 36. Added r.Streaming.GroupBoost.HugeRocTextureFactor = 0.8
; 37. Added r.Streaming.GroupBoost.LandscapeHLODTextureFactor = 0.8
; 38. Added r.Streaming.GroupBoost.LargeBuildingTextureFactor = 0.8
; 39. Added r.Streaming.GroupBoost.LargeFoliageTextureFactor = 0.8
; 40. Added r.Streaming.GroupBoost.LargeMonsterTextureFactor = 0.8
; 41. Added r.Streaming.GroupBoost.LargeNpcTextureFactor = 0.8
; 42. Added r.Streaming.GroupBoost.LargePropTextureFactor = 0.8
; 43. Added r.Streaming.GroupBoost.LargeRocTextureFactor = 0.8
; 44. Added r.Streaming.GroupBoost.MediumBuildingTextureFactor = 0.8
; 45. Added r.Streaming.GroupBoost.MediumFoliageTextureFactor = 0.8
; 46. Added r.Streaming.GroupBoost.MediumMonsterTextureFactor = 0.8
; 47. Added r.Streaming.GroupBoost.MediumNpcTextureFactor = 0.8
; 48. Added r.Streaming.GroupBoost.MediumPropTextureFactor = 0.8
; 49. Added r.Streaming.GroupBoost.MediumRocTextureFactor = 0.8
; 50. Added r.Tonemapper.Sharpen = 1.5
; 51. Removed foliage.MinimumScreenSize (was 0.15)
; 52. Removed r.Android.DisableVulkanSupport (was 0)
; 53. Removed r.BBM.LODBias (was 0)
; 54. Removed r.CullDistanceVolume.Enable (was 1)
; 55. Removed r.DefaultBackBufferPixelFormat (was 0)
; 56. Removed r.EarlyZPass (was 2)
; 57. Removed r.EarlyZPassMovable (was 1)
; 58. Removed r.GPUScene.InstanceBVH (was 1)
; 59. Removed r.GPUScene2.SupportShaders (was 0)
; 60. Removed r.HZBOcclusion (was 1)
; 61. Removed r.Kuro.Foliage.EnableFoliageCulling (was 1)
; 62. Removed r.Kuro.Foliage.MobileCullDistanceMax (was 12000)
; 63. Removed r.Kuro.Foliage.MobileGrass3_0CullDistanceMax (was 10000)
; 64. Removed r.Kuro.Foliage.MobileImpostorFarCullDistanceMax (was 55000)
; 65. Removed r.Kuro.MobileISMDecideDistance (was 9000)
; 66. Removed r.Kuro.MobileISMMeshRadius (was 550)
; 67. Removed r.Kuro.MobileISMMeshRadiusMax (was 14000)
; 68. Removed r.Kuro.ToonEyeTransparentDrawDistanceMobile (was 280)
; 69. Removed r.Kuro.ToonFaceShadowMeshDrawDistanceMobile (was 280)
; 70. Removed r.Kuro.ToonOutlineDrawDistanceMobile (was 550)
; 71. Removed r.MeshDrawCommands.MobileBasePassDrawcallLimit (was 16000)
; 72. Removed r.MeshDrawCommands.ShadowPerBatchDrawcallMax (was 140)
; 73. Removed r.MinScreenRadiusForCSMDepth (was 0.015)
; 74. Removed r.MinScreenRadiusForLights (was 0.05)
; 75. Removed r.Mobile.DisableLocalLightSpecularDistance (was 15000000)
; 76. Removed r.MotionBlurQuality (was 0)
; 77. Removed r.ParallelVelocity (was 1)
; 78. Removed r.ParticleLODBias (was 0)
; 79. Removed r.PSO.CacheEvictScheme (was 1)
; 80. Removed r.pso.evictiontime (was 20)
; 81. Removed r.RHICmdMergeSmallDeferredContexts (was 1)
; 82. Removed r.RHICmdUseDeferredContexts (was 1)
; 83. Removed r.SceneColorFormat (was 4)
; 84. Removed r.Shadow.AllShadowDrawcallMax (was 300)
; 85. Removed r.Shadow.ForbidHISMShadowStartIndex (was 2)
; 86. Removed r.Shadow.MaxResolution (was 256)
; 87. Removed r.Shadow.PerObjectResolutionMin (was 64)
; 88. Removed r.Shadow.RadiusThresholdOverrideEnable (was 0)
; 89. Removed r.ShadowMask.Scale (was 0.9)
; 90. Removed r.SSR.HalfResSceneColor (was 1)
; 91. Removed r.Streaming.FullyLoadUsedTextures (was 0)
; 92. Removed r.Streaming.UseBackgroundThreadPool (was 1)
; 93. Removed r.Streaming.UseMaterialData (was 1)
; 94. Removed r.Streaming.UseNewMetrics (was 1)
; 95. Removed r.Streaming.UsePerTextureBias (was 1)
; 96. Removed r.TemporalAA.AllowDownsampling (was 1)
; 97. Removed r.TemporalAA.MobileUpsampling (was 1)
; 98. Removed r.TemporalAA.Upscaler (was 1)
; 99. Removed r.TemporalAACurrentFrameWeight (was 0.25)
; 100. Removed r.UseKuroBasePassSortKeyToon (was 30)
; 101. Removed r.UseKuroCopyTexture (was 1)
; 102. Removed r.UsePreExposure (was 1)
; 103. Removed r.UseVisibilityOctree (was 0)
; 104. Removed r.VirtualTexturedLightmaps (was 1)
; 105. Removed r.VT.EnableCompressCrunch (was 1)
; 106. Removed r.VT.EnableCompressZlib (was 1)
; 107. Removed r.VT.EnableFeedback (was 1)
; 108. Removed r.VT.FeedbackFactor (was 4)
; 109. Removed r.VT.MaskedPageTableUpdates (was 1)
; 110. Removed r.VT.MaxAnisotropy (was 4)
; 111. Removed r.VT.MaxUploadsPerFrame (was 4)
; 112. Removed r.VT.NumFeedbackTasks (was 2)
; 113. Removed r.VT.NumGatherTasks (was 1)
; 114. Removed r.VT.ParallelFeedbackTasks (was 1)
; 115. Removed r.VT.TileBorderSize (was 4)
; 116. Removed r.VT.TileSize (was 64)
; 117. Removed s.FlushStreamingOnExit (was 1)
; 118. Removed s.IoDispatcherBufferSizeKB (was 256)
; 119. Removed s.LevelStreamingComponentsRegistrationGranularity (was 5)
; 120. Removed s.LevelStreamingComponentsUnregistrationGranularity (was 2)
; 121. Removed s.UseBackgroundLevelStreaming (was 1)
; 122. Removed s.WarnIfTimeLimitExceeded (was 0)
; 123. a.URO.ForceAnimRate changed from 2 to 1
; 124. r.Kuro.Foliage.MobileMiddleCullDistanceMax changed from 22000 to 20000
; 125. r.Kuro.Foliage.MobileNearCullDistanceMax changed from 8000 to 10000
; 126. r.Kuro.Foliage.MobileSuperFarCullDistanceMax changed from 45000 to 30000
; 127. r.Kuro.KuroBloomStreak changed from 0 to 3
; 128. r.MobileNumDynamicPointLights changed from 2 to 4
; 129. r.ReflectionCaptureResolution changed from 64 to 128
; 130. r.RHICmdBypass changed from 1 to 0
; 131. r.ScreenSizeCullRatioFactor changed from 2 to 2.0
; 132. r.Shadow.DistanceScale changed from 0.8 to 1.2
; 133. r.Shadow.PerObjectResolutionMax changed from 512 to 1024
; 134. r.Shadow.RadiusThreshold changed from 0.03 to 0.02
; 135. r.SSR.MaxRoughness changed from 1.0 to 0.9
; 136. r.SSR.Quality changed from 4 to 3
; 137. r.TemporalAA.MobileFrameWeight changed from 0.12 to 0.25
; 138. r.TemporalAAFilterSize changed from 0.5 to 1.0
; 139. r.Tonemapper.Quality changed from 4 to 5
; 140. r.TonemapperGamma changed from 2.05 to 2.0
; 141. s.AsyncLoadingTimeLimit changed from 2.0 to 5
; 142. s.IoDispatcherBufferMemoryMB changed from 128 to 256
; 143. s.IoDispatcherCacheSizeMB changed from 32 to 64
; 144. s.LevelStreamingActorsUpdateTimeLimit changed from 6.0 to 10.0
; 145. s.PriorityLevelStreamingActorsUpdateExtraTime changed from 6.0 to 10.0
; 146. s.UnregisterComponentsTimeLimit changed from 1.0 to 2.0
; 147. wp.Runtime.LoadingRangeScale changed from 0.6 to 0.8
; 148. wp.Runtime.PlannedLoadingRangeScale changed from 0.75 to 1.0
[SystemSettings]
a.URO.Enable=1
a.URO.ForceAnimRate=2
a.URO.ForceInterpolation=1
r.Color.Mid=0.45
Kuro.Blueprint.EnableGameBudget=1 ;set to 0 if u want honami escalator moving
r.GPUScene.ParallelUpdate=1
r.GPUScene.UploadEveryFrame=1
r.GPUSkin.EnablePool=1
r.GPUSkin.Support16BitBoneIndex=1
r.ParallelBasePass=1
r.ParallelPrePass=1
r.ParallelSingleLayerWaterPass=1
r.ParallelTranslucency=1
r.PostProcessAAQuality=4
r.PSO.CompilationMode=0
r.ReflectionCaptureResolution=128
r.RHICmdAsyncRHIThreadDispatch=1
r.RHICmdBypass=0
r.RHICmdUseParallelAlgorithms=1
r.RHICmdUseThread=1
r.ShaderPipelineCache.Enabled=1
r.ShaderPipelineCache.SaveUserCache=1
r.ShaderPipelineCache.StartupMode=1
r.ShaderPipelines=1
r.SSR.MaxRoughness=0.7
r.SSR.Quality=2
r.SSR.Temporal=1
r.SSR.HalfResSceneColor=1
r.StaticMeshLODDistanceScale=0.95
r.TemporalAA.Algorithm=1
r.TemporalAA.HistoryScreenPercentage=80
r.TemporalAA.MobileFrameWeight=0.25
r.TemporalAA.Upsampling=1
r.TemporalAACatmullRom=1
r.TemporalAAFilterSize=1.0
r.Tonemapper.Quality=5
r.Tonemapper.Sharpen=1.5
r.TonemapperGamma=2.0
r.Upscale.Quality=3
r.UseClusteredDeferredShading=1
r.VirtualTexture=1
r.VT.MaxUploadsPerFrame=2
r.VT.MaxUploadsPerFrame.Streaming=4

[/Script/Engine.RendererSettings]
foliage.LODDistanceScale=1.0
r.DistanceFieldAO=1
r.Kuro.AutoCoolEnable=0
r.Kuro.Foliage.GrassCullDistanceMax=18000
r.Kuro.Foliage.MobileNearCullDistanceMax=10000
r.Kuro.Foliage.MobileMiddleCullDistanceMax=20000
r.Kuro.Foliage.MobileSuperFarCullDistanceMax=30000
r.Kuro.InteractionEffect.UseCppWaterEffect=1
r.Kuro.KuroBloomStreak=3
r.MobileLightShaft=1
r.MobileLightShaft.AllowTAA=1
r.MobileLightShaft.NumSamples=8
r.LightShaftNumSamples=12
r.LightShaftQuality=1
r.MobileNumDynamicPointLights=4
r.ScreenSizeCullRatioFactor=2.0
r.Shadow.CSM.MaxCascades=4
r.Shadow.CSM0Distance=1000
r.Shadow.CSM1Distance=1500
r.Shadow.CSM2Distance=5000
r.Shadow.DistanceScale=1.2
r.Shadow.PerObjectResolutionMax=768
r.Shadow.RadiusThreshold=0.02
wp.Runtime.LoadingRangeScale=0.8
wp.Runtime.PlannedLoadingRangeScale=1.0

[/Script/Engine.StreamingSettings]
r.TextureStreaming=1
s.AsyncLoadingTimeLimit=5
s.AsyncLoadingThreadEnabled=1
s.EventDrivenLoaderEnabled=1
s.IoDispatcherBufferMemoryMB=256
s.IoDispatcherCacheSizeMB=64
s.LevelStreamingActorsUpdateTimeLimit=10.0
s.PriorityLevelStreamingActorsUpdateExtraTime=10.0
s.UnregisterComponentsTimeLimit=2.0
r.Streaming.GroupBoost.HugeMonsterTextureFactor=0.8
r.Streaming.GroupBoost.LargeMonsterTextureFactor=0.8
r.Streaming.GroupBoost.MediumMonsterTextureFactor=0.8
r.Streaming.GroupBoost.HugeNpcTextureFactor=0.8
r.Streaming.GroupBoost.LargeNpcTextureFactor=0.8
r.Streaming.GroupBoost.MediumNpcTextureFactor=0.8
r.Streaming.GroupBoost.HugeRocTextureFactor=0.8
r.Streaming.GroupBoost.LargeRocTextureFactor=0.8
r.Streaming.GroupBoost.MediumRocTextureFactor=0.8
r.Streaming.GroupBoost.HugeFoliageTextureFactor=0.8
r.Streaming.GroupBoost.LargeFoliageTextureFactor=0.8
r.Streaming.GroupBoost.MediumFoliageTextureFactor=0.8
r.Streaming.GroupBoost.HugeBuildingTextureFactor=0.8
r.Streaming.GroupBoost.LargeBuildingTextureFactor=0.8
r.Streaming.GroupBoost.MediumBuildingTextureFactor=0.8
r.Streaming.GroupBoost.HugePropTextureFactor=0.8
r.Streaming.GroupBoost.LargePropTextureFactor=0.8
r.Streaming.GroupBoost.MediumPropTextureFactor=0.8
r.Streaming.GroupBoost.CommonHLODTextureFactor=0.8
r.Streaming.GroupBoost.LandscapeHLODTextureFactor=0.8

[/Script/Engine.GarbageCollectionSettings]
gc.ActorClusteringEnabled=1
gc.AllowParallelGC=1
gc.CreateGCClusters=1
gc.FlushStreamingOnGC=0
gc.MaxObjectsInGame=2000000
gc.MaxObjectsNotConsideredByGC=80000
gc.MinDesiredObjectsPerSubTask=128
gc.MultithreadedDestructionEnabled=1
gc.SizeOfPermanentObjectPool=33554432
gc.TimeBetweenPurgingPendingKillObjects=60.0

[Core.System]
Paths=../../../Engine/Content
Paths=%GAMEDIR%Content
Paths=../../../Engine/Plugins/ThirdParty/ImpostorBaker/Content
Paths=../../../Engine/Plugins/json2struct/Content
Paths=../../../Engine/Plugins/Experimental/FieldSystemPlugin/Content
Paths=../../../Client/Plugins/LGUI/LGUI/Content
Paths=../../../Engine/Plugins/PrefabSystem/Content
Paths=../../../Engine/Plugins/FX/Niagara/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplay/Content
Paths=../../../Client/Plugins/Puerts/Puerts/Content
Paths=../../../Client/Plugins/Wwise/Content
Paths=../../../Engine/Plugins/Editor/GeometryMode/Content
Paths=../../../Engine/Plugins/MovieScene/SequencerScripting/Content
Paths=../../../Engine/Plugins/Experimental/PythonScriptPlugin/Content
Paths=../../../Client/Plugins/CrashSight/Content
Paths=../../../Engine/Plugins/ThirdParty/QuickEditor/Content
Paths=../../../Client/Plugins/Sharphereal/Content
Paths=../../../Engine/Plugins/Experimental/GeometryProcessing/Content
Paths=../../../Client/Plugins/Kuro/TASdkPlugin/Content
Paths=../../../Engine/Plugins/rdLODtools/Content
Paths=../../../Client/Plugins/AudioMaterialPlugin/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/DLSS/Content
Paths=../../../Engine/Plugins/Runtime/HoudiniEngine/Content
Paths=../../../Client/Plugins/Kuro/KuroHotPatch/Content
Paths=../../../Client/Plugins/Kuro/KuroImposter/Content
Paths=../../../Client/Plugins/Kuro/KuroAutomationTool/Content
Paths=../../../Engine/Plugins/FX/HoudiniNiagara/Content
Paths=../../../Client/Plugins/LogicDriverLite/Content
Paths=../../../Engine/Plugins/Runtime/AudioSynesthesia/Content
Paths=../../../Engine/Plugins/Experimental/ControlRig/Content
Paths=../../../Engine/Plugins/Media/MediaCompositing/Content
Paths=../../../Engine/Plugins/Runtime/Synthesis/Content
Paths=../../../Engine/Plugins/SequenceDialogue/Content
Paths=../../../Client/Plugins/Puerts/ReactUMG/Content
Paths=../../../Client/Plugins/genesis-ue-plugin/RenderExporter/Content
Paths=../../../Engine/Plugins/KuroiOSDelegate/Content
Paths=../../../Client/Plugins/Kuro/KuroCloudGame/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplayUI/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/OpacityMicroMap/Content
Paths=../../../Client/Plugins/BlockoutToolsPlugin/Content
Paths=../../../Client/Plugins/ComfyTextures/Content
Paths=../../../Client/Plugins/KuroComputeShader/Content
Paths=../../../Client/Plugins/KuroTDM/Content
Paths=../../../Client/Plugins/Kuro/ImposterBaker/Content
Paths=../../../Client/Plugins/Kuro/KuroGachaTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPSOTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPushSdk/Content
Paths=../../../Client/Plugins/SdkParamExtend/Content
Paths=../../../Client/Plugins/SpinePlugin/Content
Paths=../../../Client/Plugins/TpSafe/Content
Paths=../../../Engine/Plugins/AFME/Content
Paths=../../../Engine/Plugins/Animation/ACLPlugin/Content
Paths=../../../Engine/Plugins/AssetChecker/Content
Paths=../../../Engine/Plugins/AssetMemoryAnalyzer/Content
Paths=../../../Engine/Plugins/DawnSDK/DawnSDK/Content
Paths=../../../Engine/Plugins/Dawn/Content
Paths=../../../Engine/Plugins/Editor/SpeedTreeImporter/Content
Paths=../../../Engine/Plugins/Experimental/ChaosClothEditor/Content
Paths=../../../Engine/Plugins/Experimental/ChaosNiagara/Content
Paths=../../../Engine/Plugins/Experimental/ChaosSolverPlugin/Content
Paths=../../../Engine/Plugins/GSR/Content
Paths=../../../Engine/Plugins/MFRCModule/Content
Paths=../../../Engine/Plugins/Runtime/Intel/XeSS/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/NRD/Content
Paths=../../../Client/Plugins/Kuro/KRDataAnalyticsPlugin/Content
Paths=../../../Engine/Plugins/Experimental/ColorCorrectRegions/Content
Paths=../../../Engine/Plugins/Compositing/OpenCVLensDistortion/Content
Paths=../../../Engine/Plugins/Experimental/FastGeoStreaming/Content
Paths=../../../Client/Plugins/Kuro/KuroWorldPartition/Content
Paths=../../../Client/Plugins/Kuro/KuroDynamicMeshBatch/Content
Paths=../../../Client/Plugins/Kuro/KuroPerfCat/Content
Paths=../../../Client/Plugins/MeshBlend/Content
Paths=../../../Client/Plugins/TFlow/Content
Paths=../../../Engine/Plugins/KuroFI/Content
Paths=../../../Engine/Plugins/MagicDawn/Content
Paths=../../../Engine/Plugins/MTKCompensatedTimeStep/Content
Paths=../../../Engine/Plugins/MagtModule/Content
---
