; ============================================================
; Potato Config Link: https://github.com/Arglax/Mobile-WuWa-Config/tree/main/%5BV3.x%5D%20Working%20Configs/Potato%20Config
;_____________________________________________________________
; September 3, 2026
; ============================================================
; 			Final Notes
; Potato Config with High-Quality Material (SG groups zeroed)
; If this doesn't work for you, check out CVW's discord
;	Config Main Repository: https://github.com/Arglax/Mobile-WuWa-Config/
; ============================================================
; 			References Used:
; 1. Archived Mobile Configs by AlteriaX 	(https://github.com/AlteriaX/WuWa-Configs-Android/tree/main)
; 2. UE Official CVar Reference 	(https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-console-variables-reference)
; ====================END OF MAIN NOTES=======================

[Android_Lowest DeviceProfile]
DeviceScore=6969
