; ============================================================
; Potato Config Link: https://github.com/Arglax/Mobile-WuWa-Config/tree/main/%5BV3.x%5D%20Working%20Configs/Potato%20Config
;_____________________________________________________________
; February 21, 2026 (Recommended Update)
; 1. Update deviceprofiles list and adjusted cvars values for performance
; 2. Further optimized for better performance
; February 17, 2026 (Recommended Update)
; 1. Updated DeviceProfiles (please give me some time to list all updated gpu family)
; 2. Relowered some values
; 3. Increased streaming poolsize from 512
; January 19, 2026 (Optional Update)
; 1. Expanded Devices list.
; January 11, 2025
; 1. Created the config.
; ============================================================
; 			Final Notes
; Potato Config with High-Quality Material (SG groups zeroed)
; 1. If it does not work for you, delete ONLY this deviceprofile.
;   1.a Request a custom POTATO config in the discord. It will become my basis for future potato configs.
;	Config Main Repository: https://github.com/Arglax/Mobile-WuWa-Config/
; ============================================================
; 			References Used:
; 1. Archived Mobile Configs by AlteriaX 	(https://github.com/AlteriaX/WuWa-Configs-Android/tree/main)
; 2. UE Official CVar Reference 	(https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-console-variables-reference)
; ====================END OF MAIN NOTES=======================

[Potato DeviceProfile]
;Cvars=r.MobileContentScaleFactor=1.00   ;change to 0.80-1.40 for better performance
;CVars=r.SecondaryScreenPercentage.GameViewport=77
Cvars=r.Mobile.HighQualityMaterial=0  ;1 for better graphics
Cvars=r.Android.DisableVulkanSupport=0  ;change to 1 if you have vulkan rendering problems
Cvars=wp.Runtime.LoadingRangeScale=0.80
;sg groups
CVars=sg.ViewDistanceQuality=0
CVars=sg.AntiAliasingQuality=0
CVars=sg.ShadowQuality=0
CVars=sg.PostProcessQuality=0
CVars=sg.TextureQuality=0
CVars=sg.EffectsQuality=0
CVars=sg.FoliageQuality=0   ; for perf
CVars=sg.ShadingQuality=0

[Android_Default DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_TegraK1 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G61x DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_Immortalis DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_Gx_Ultra DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G92x DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_MTK_6991 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_IMG_BXM DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G57_MC2 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G720 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno_7xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno740 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno_6xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno825 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno840 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno830 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno_8xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno810 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Xclipse9xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Xclipse940 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno7xx_Low DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Xclipse930 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Xclipse5xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G68 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Tensor_G4 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Tensor_G3 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000