;		WuWa Mobile Config for Version 3.5
; 		    Last Modified by: Arglax
; ============================================================
; 			Performance Config (Config_1)
; Link: https://github.com/Arglax/Mobile-WuWa-Config/tree/main/%5BV3.x%5D%20Working%20Configs/Performance%20Configs/Config_1
; ============================================================
; 		Change to your GPUFamily
; Link for PC Tutorial: https://youtu.be/gtmyFKGyl1M
; Link for Mobile Tutorial: https://youtube.com/shorts/ygf6GUBkx18
; Changes
; 1. Adjusted values and cleaned up forbidden cvars
; 2. bike issue on frame gen patch, credits to k4irzw67
; ============================================================
; 			Final Notes
; - Lowered some values
; - Added maxfps
; 1. There is a dedicated READMe.md for this performance config. Please read it.
;	READme Link: https://github.com/Arglax/Mobile-WuWa-Config/tree/main/%5BV3.x%5D%20Working%20Configs/Performance%20Configs/Config_1/README.md
; 2. This DeviceProfiles.ini is plug and play. No required edits or changes in order to apply.
; ============================================================

[Android_Low DeviceProfile]
DeviceScore=6969
CVars=t.MaxFPS=120
Cvars=r.Android.DisableVulkanSupport=0
Cvars=r.Android.VulkanSetting=1
CVars=sg.TextureQuality=3
CVars=wp.Runtime.LoadingRangeScale=0.75
CVars=wp.Runtime.PlannedLoadingRangeScale=0.90
CVars=r.KuroFI.InternalResolutionScale=0.5
CVars=a.URO.Enable=1
Cvars=a.URO.ForceAnimRate=3 ;set to 2 if chars feel weird for u
CVars=a.URO.ForceInterpolation=1